# Generated by Django 3.1 on 2020-08-14 10:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_historicalrolepermission_rolepermission_staffuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStaffUser',
            fields=[
                ('users_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='accounts.users')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_index=True, max_length=100, verbose_name='Username')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Last name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Account active')),
                ('is_staff', models.BooleanField(default=True, help_text='Designates whether the user can log into this portal.', verbose_name='staff status')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Staff User',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='group_ptr',
        ),
        migrations.AlterModelOptions(
            name='historicalusers',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Customer'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Customer', 'verbose_name_plural': '  Customers'},
        ),
        migrations.AlterField(
            model_name='bankaccounts',
            name='account_number',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12)], verbose_name='Account number'),
        ),
        migrations.AlterField(
            model_name='historicalbankaccounts',
            name='account_number',
            field=models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12)], verbose_name='Account number'),
        ),
        migrations.DeleteModel(
            name='HistoricalRolePermission',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.AddField(
            model_name='historicalstaffuser',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstaffuser',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group', verbose_name='Role'),
        ),
    ]
