# Generated by Django 3.1 on 2020-08-14 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_model_changes.changes
import modules.bankings.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Label')),
                ('translation', models.CharField(default=modules.bankings.models.trans_generator, max_length=100, unique=True, verbose_name='Transaction id')),
                ('trans_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Enquiry', 'Enquiry')], max_length=30, verbose_name='Transaction type')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('status', models.BooleanField(default=True, verbose_name='Transaction status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': '  Transactions',
            },
            bases=(django_model_changes.changes.ChangesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransactionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.FloatField(default=0, verbose_name='Amount total')),
                ('amount_deposit', models.FloatField(default=0, verbose_name='Amount deposit')),
                ('amount_withdraw', models.FloatField(default=0, verbose_name='Amount withdraw')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankings.transactions', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': '  Reports',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransactions',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Label')),
                ('translation', models.CharField(db_index=True, default=modules.bankings.models.trans_generator, max_length=100, verbose_name='Transaction id')),
                ('trans_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Enquiry', 'Enquiry')], max_length=30, verbose_name='Transaction type')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('status', models.BooleanField(default=True, verbose_name='Transaction status')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Transaction',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
